### ISSUE TITLE
dataTable.js 已选择项回显问题

### ISSUE THREAD

**Issue by Code-Pang** [fbackend/WFUI#1]
dataTable.js checkedData  怎么放在外部供设置checkedData

**Comment by zmapleshine** [comment]
> dataTable.js checkedData 怎么放在外部供设置checkedData

datatable实例化后的对象提供getCheckedData()方法，不知是否满足你的需求？

**Comment by qingyangQAQ** [comment]
> > dataTable.js CheckedData如何放置外部供设置checkedData
> 
> datatable实例化后的对象提供getCheckedData（）方法，不知是否满足你的需求？

请进一步详细描述需求

**Comment by Code-Pang** [comment]
datatable实例化后的对象提供getCheckedData 只能到已经选择的数组，如果是想对于添加多选框的table 设置初始值和勾选状态，有无可用的方法，例如setCheckedData 或其他方法。
目前遇到的场景就是  对于打开的table 赋予初始值和选中状态，源码内没发现有相关API可供使用



752456184@qq.com
 
发件人： qingyangQAQ
发送时间： 2020-05-23 22:17
收件人： fbackend/WFUI
抄送： 752456184@qq.com; Author
主题： Re: [fbackend/WFUI] dataTable.js 已选择项回显问题 (#1)
dataTable.js CheckedData如何放置外部供设置checkedData
datatable实例化后的对象提供getCheckedData（）方法，不知是否满足你的需求？
请进一步详细描述需求
―

**Comment by zmapleshine** [comment]
@Code-Pang 0.0.1.RELEASE 已发布，已提供‘’显式赋予选中‘’的功能在datatable模块。
